#!/bin/bash

USR="Your Username goes here"
PASSWD="Your Password goes here"
HOST="Your Hostname or IP Address goes here"
PORT="Your database port number goes here"
DB="Your Database name goes here"
TABLE="Your table name goes here"

mysql -u ${USR} -p${PASSWD} -h ${HOST}:${PORT} -e 'SELECT TABLE_SCHEMA AS SRC_DB, TABLE_NAME AS SRC_TABLE, COLUMN_NAME AS SRC_COLUMN, REFERENCED_TABLE_SCHEMA AS REF_DB, REFERENCED_TABLE_NAME AS REF_TABLE, REFERENCED_COLUMN_NAME AS REF_COLUMN FROM KEY_COLUMN_USAGE WHERE TABLE_SCHEMA  = "${DB}" AND TABLE_NAME = "${TABLE}" AND REFERENCED_TABLE_NAME IS NOT NULL;'

mysql -u ${USR} -p${PASSWD} -h ${HOST}:${PORT} -e 'SELECT R.CONSTRAINT_SCHEMA AS DB_NAME, R.TABLE_NAME AS SRC_TABLE, K.COLUMN_NAME AS SRC_COLUMN, T.CONSTRAINT_TYPE AS TYPE, R.REFERENCED_TABLE_NAME AS REF_TABLE, K.REFERENCED_COLUMN_NAME AS REF_COLUMN FROM REFERENTIAL_CONSTRAINTS R JOIN KEY_COLUMN_USAGE K ON R.CONSTRAINT_NAME = K.CONSTRAINT_NAME JOIN TABLE_CONSTRAINTS T ON R.CONSTRAINT_NAME = T.CONSTRAINT_NAME AND R.CONSTRAINT_SCHEMA = "${DB}" AND R.TABLE_NAME = "${TABLE}";'
