#!/bin/bash

USR="Your Username goes here"
PASSWD="Your Password goes here"
HOST="Your Hostname or IP Address goes here"
PORT="Your database port number goes here"
DB="Your Database name goes here"
TABLE="Your table name goes here"

mysql -u ${USR} -p${PASSWD} -h ${HOST}:${PORT} -e 'SELECT TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,REFERENCED_TABLE_SCHEMA,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE WHERE INFORMATION_SCHEMA.TABLE_SCHEMA = ${DB} AND INFORMATION_SCHEMA.REFERENCED_TABLE_NAME IS NOT NULL;'

# Foreign key relations
mysql -u ${USR} -p${PASSWD} -h ${HOST}:${PORT} -e 'SELECT CONSTRAINT_SCHEMA,CONSTRAINT_NAME,TABLE_SCHEMA,TABLE_NAME,CONSTRAINT_TYPE FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE INFORMATION_SCHEMA.CONSTRAINT_TYPE LIKE "%FOREIGN%" AND INFORMATION_SCHEMA.TABLE_SCHEMA = ${DB};'

# Primary key relations
mysql -u ${USR} -p${PASSWD} -h ${HOST}:${PORT} -e 'SELECT CONSTRAINT_SCHEMA,CONSTRAINT_NAME,TABLE_SCHEMA,TABLE_NAME,CONSTRAINT_TYPE FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE INFORMATION_SCHEMA.CONSTRAINT_TYPE LIKE "%PRIMARY%" AND INFORMATION_SCHEMA.TABLE_SCHEMA = ${DB};'
