--SELECT 
--  `TABLE_SCHEMA`,                          -- Foreign key schema
--  `TABLE_NAME`,                            -- Foreign key table
--  `COLUMN_NAME`,                           -- Foreign key column
--  `REFERENCED_TABLE_SCHEMA`,               -- Origin key schema
--  `REFERENCED_TABLE_NAME`,                 -- Origin key table
--  `REFERENCED_COLUMN_NAME`                 -- Origin key column
--FROM
--  `INFORMATION_SCHEMA`.`KEY_COLUMN_USAGE`  -- Will fail if user don't have privilege
--WHERE
--  `TABLE_SCHEMA` = SCHEMA()                -- Detect current schema in USE 
--  AND `REFERENCED_TABLE_NAME` IS NOT NULL; -- Only tables with foreign keys

SELECT TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,REFERENCED_TABLE_SCHEMA,REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME FROM KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = DATABASE_NAME() AND REFERENCED_TABLE_NAME IS NOT NULL;

SELECT CONSTRAINT_SCHEMA,CONSTRAINT_NAME,TABLE_SCHEMA,TABLE_NAME,CONSTRAINT_TYPE FROM TABLE_CONSTRAINTS where CONSTRAINT_TYPE like "%FOREIGN%" AND TABLE_SCHEMA = DATABASE_NAME();
SELECT CONSTRAINT_SCHEMA,CONSTRAINT_NAME,TABLE_SCHEMA,TABLE_NAME,CONSTRAINT_TYPE FROM TABLE_CONSTRAINTS where CONSTRAINT_TYPE like "%PRIMARY%" AND TABLE_SCHEMA = DATABASE_NAME();
